{% set name = "pikepdf" %}
{% set version = "9.4.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 03fb70ff4fada9cba864d04033f4166b5bf7fa85c90cdc05afd0ab87c9ccaa1a
  patches:
    - 0001-update-paths.patch

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv
  skip: true  # [py<38]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - patch  # [not win]
    - m2-patch  # [win]
  host:
    - python
    - pip
    - setuptools_scm >=7.0.5
    - wheel
    - pybind11 >=2.12.0
    - qpdf
  run:
    - python
    - setuptools
    - deprecation
    - lxml >=4.8
    - qpdf >=10.6.2
    - pillow >=10.0.1
    - packaging

test:
  source_files:
    - tests
  imports:
    - pikepdf
  requires:
    - pytest >=6.2.5
    - python-dateutil >=2.8.1
    - attrs >=20.2.0
    - hypothesis >=6.36
    - numpy >=1.21  # [x86_64]
    - psutil >=5.9  # [not win]
    - tomli  # [py<311]
  commands:
    - pytest tests

about:
  home: https://github.com/pikepdf/pikepdf
  license: MPL-2.0
  license_family: OTHER
  license_file: LICENSE.txt
  summary: A Python library for reading and writing PDF, powered by qpdf
  doc_url: https://pikepdf.readthedocs.io/
  dev_url: https://github.com/pikepdf/pikepdf

extra:
  recipe-maintainers:
    - carlodri
