{% set name = "pikepdf" %}
{% set version = "9.4.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 0108c063bc56dc2dbfc87f20533a728342a938f4c85e39773866b71255aa8388
  patches:
    - 0001-update-paths.patch
    - 0002-fix-test.patch
    - 0003-do-not-require-deprecated.patch

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv
  # skip s390x because of missing qpdf
  skip: true  # [py<38 or s390x]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - patch  # [not win]
    - m2-patch  # [win]
  host:
    - python
    - pip
    - setuptools >=61
    - wheel
    - pybind11 2.12.0
    - qpdf 11.9.1
  run:
    - python
    - deprecation
    - lxml >=4.8
    - qpdf >=10.6.2
    - pillow >=10.0.1
    - packaging

test:
  source_files:
    - tests
  imports:
    - pikepdf
  requires:
    - pip
    - pytest >=6.2.5
    - python-dateutil >=2.8.1
    - attrs >=20.2.0
    - hypothesis
    - numpy >=1.21  # [x86_64]
    - psutil >=5.9  # [not win]
    - tomli  # [py<311]
  commands:
    - pip check
    - pytest tests

about:
  home: https://github.com/pikepdf/pikepdf
  license: MPL-2.0
  license_family: OTHER
  license_file: LICENSE.txt
  summary: A Python library for reading and writing PDF, powered by qpdf
  description: |
    pikepdf is a Python library allowing creation, manipulation and repair of PDFs. It provides a Pythonic wrapper
    around the C++ PDF content transformation library, QPDF.
  doc_url: https://pikepdf.readthedocs.io
  dev_url: https://github.com/pikepdf/pikepdf

extra:
  recipe-maintainers:
    - carlodri
  skip-lints:
    - invalid_url
